import Footer from "../../layouts/footer/Footer";
import Header from "../../layouts/header/Header";
import SideBar from "../../layouts/sidebar/SideBar";
import styles from "../../layouts/layout.module.scss";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Main menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className={styles.wrapper}>
          <Header />
          <SideBar />
          <main className={styles.main}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
