import Footer from "../../layouts/footer/Footer";
import Header from "../../layouts/header/Header";
import SideBar from "../../layouts/sidebar/SideBar";
import styles from "../../layouts/layout.module.scss";
import type { Metadata } from "next";
import { AppContextProvider, IAppContext } from "../../context/app.context";

export const metadata: Metadata = {
  title: "Main menu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <div className={styles.wrapper}>
            <Header />
            <SideBar />
            <main className={styles.main}>{children}</main>
            <Footer />
          </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
